//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.isapi.org/ver20/XMLSchema", IsNullable = false)]
public partial class DeviceCap
{

    private bool isSupportRebootField;

    private bool isSupportFactoryResetField;

    private bool isSupportUpdatefirmwareField;

    private bool isSupportDeviceInfoField;

    private DeviceCapSysCap sysCapField;

    private byte voicetalkNumsField;

    private bool isSupportSnapshotField;

    private DeviceCapSecurityCap securityCapField;

    private object eventCapField;

    private DeviceCapRacmCap racmCapField;

    private bool isSupportEhomeField;

    private object videoIntercomCapField;

    private bool isSupportAcsUpdateField;

    private bool isSupportEncryptionField;

    private bool supportImageChannelField;

    private bool isSupportImageCapField;

    private bool isSupportPictureServerField;

    private bool isSupportAlgorithmsInfoField;

    private bool isSupportAccessControlCapField;

    private bool isSupportClientProxyWEBField;

    private string wEBLocationField;

    private bool isSupportUserManualQRCodeField;

    private bool isSupportEZVIZParameterTestField;

    private bool isSupportLocalUserChangeField;

    private decimal versionField;

    /// <remarks/>
    public bool isSupportReboot
    {
        get
        {
            return this.isSupportRebootField;
        }
        set
        {
            this.isSupportRebootField = value;
        }
    }

    /// <remarks/>
    public bool isSupportFactoryReset
    {
        get
        {
            return this.isSupportFactoryResetField;
        }
        set
        {
            this.isSupportFactoryResetField = value;
        }
    }

    /// <remarks/>
    public bool isSupportUpdatefirmware
    {
        get
        {
            return this.isSupportUpdatefirmwareField;
        }
        set
        {
            this.isSupportUpdatefirmwareField = value;
        }
    }

    /// <remarks/>
    public bool isSupportDeviceInfo
    {
        get
        {
            return this.isSupportDeviceInfoField;
        }
        set
        {
            this.isSupportDeviceInfoField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSysCap SysCap
    {
        get
        {
            return this.sysCapField;
        }
        set
        {
            this.sysCapField = value;
        }
    }

    /// <remarks/>
    public byte voicetalkNums
    {
        get
        {
            return this.voicetalkNumsField;
        }
        set
        {
            this.voicetalkNumsField = value;
        }
    }

    /// <remarks/>
    public bool isSupportSnapshot
    {
        get
        {
            return this.isSupportSnapshotField;
        }
        set
        {
            this.isSupportSnapshotField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSecurityCap SecurityCap
    {
        get
        {
            return this.securityCapField;
        }
        set
        {
            this.securityCapField = value;
        }
    }

    /// <remarks/>
    public object EventCap
    {
        get
        {
            return this.eventCapField;
        }
        set
        {
            this.eventCapField = value;
        }
    }

    /// <remarks/>
    public DeviceCapRacmCap RacmCap
    {
        get
        {
            return this.racmCapField;
        }
        set
        {
            this.racmCapField = value;
        }
    }

    /// <remarks/>
    public bool isSupportEhome
    {
        get
        {
            return this.isSupportEhomeField;
        }
        set
        {
            this.isSupportEhomeField = value;
        }
    }

    /// <remarks/>
    public object VideoIntercomCap
    {
        get
        {
            return this.videoIntercomCapField;
        }
        set
        {
            this.videoIntercomCapField = value;
        }
    }

    /// <remarks/>
    public bool isSupportAcsUpdate
    {
        get
        {
            return this.isSupportAcsUpdateField;
        }
        set
        {
            this.isSupportAcsUpdateField = value;
        }
    }

    /// <remarks/>
    public bool isSupportEncryption
    {
        get
        {
            return this.isSupportEncryptionField;
        }
        set
        {
            this.isSupportEncryptionField = value;
        }
    }

    /// <remarks/>
    public bool supportImageChannel
    {
        get
        {
            return this.supportImageChannelField;
        }
        set
        {
            this.supportImageChannelField = value;
        }
    }

    /// <remarks/>
    public bool isSupportImageCap
    {
        get
        {
            return this.isSupportImageCapField;
        }
        set
        {
            this.isSupportImageCapField = value;
        }
    }

    /// <remarks/>
    public bool isSupportPictureServer
    {
        get
        {
            return this.isSupportPictureServerField;
        }
        set
        {
            this.isSupportPictureServerField = value;
        }
    }

    /// <remarks/>
    public bool isSupportAlgorithmsInfo
    {
        get
        {
            return this.isSupportAlgorithmsInfoField;
        }
        set
        {
            this.isSupportAlgorithmsInfoField = value;
        }
    }

    /// <remarks/>
    public bool isSupportAccessControlCap
    {
        get
        {
            return this.isSupportAccessControlCapField;
        }
        set
        {
            this.isSupportAccessControlCapField = value;
        }
    }

    /// <remarks/>
    public bool isSupportClientProxyWEB
    {
        get
        {
            return this.isSupportClientProxyWEBField;
        }
        set
        {
            this.isSupportClientProxyWEBField = value;
        }
    }

    /// <remarks/>
    public string WEBLocation
    {
        get
        {
            return this.wEBLocationField;
        }
        set
        {
            this.wEBLocationField = value;
        }
    }

    /// <remarks/>
    public bool isSupportUserManualQRCode
    {
        get
        {
            return this.isSupportUserManualQRCodeField;
        }
        set
        {
            this.isSupportUserManualQRCodeField = value;
        }
    }

    /// <remarks/>
    public bool isSupportEZVIZParameterTest
    {
        get
        {
            return this.isSupportEZVIZParameterTestField;
        }
        set
        {
            this.isSupportEZVIZParameterTestField = value;
        }
    }

    /// <remarks/>
    public bool isSupportLocalUserChange
    {
        get
        {
            return this.isSupportLocalUserChangeField;
        }
        set
        {
            this.isSupportLocalUserChangeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSysCap
{

    private bool isSupportDstField;

    private DeviceCapSysCapNetworkCap networkCapField;

    private DeviceCapSysCapSerialCap serialCapField;

    private DeviceCapSysCapVideoCap videoCapField;

    private DeviceCapSysCapAudioCap audioCapField;

    private bool isSupportSubscribeEventField;

    private bool isSupportTimeCapField;

    private bool isSupportPostUpdateFirmwareField;

    /// <remarks/>
    public bool isSupportDst
    {
        get
        {
            return this.isSupportDstField;
        }
        set
        {
            this.isSupportDstField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSysCapNetworkCap NetworkCap
    {
        get
        {
            return this.networkCapField;
        }
        set
        {
            this.networkCapField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSysCapSerialCap SerialCap
    {
        get
        {
            return this.serialCapField;
        }
        set
        {
            this.serialCapField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSysCapVideoCap VideoCap
    {
        get
        {
            return this.videoCapField;
        }
        set
        {
            this.videoCapField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSysCapAudioCap AudioCap
    {
        get
        {
            return this.audioCapField;
        }
        set
        {
            this.audioCapField = value;
        }
    }

    /// <remarks/>
    public bool isSupportSubscribeEvent
    {
        get
        {
            return this.isSupportSubscribeEventField;
        }
        set
        {
            this.isSupportSubscribeEventField = value;
        }
    }

    /// <remarks/>
    public bool isSupportTimeCap
    {
        get
        {
            return this.isSupportTimeCapField;
        }
        set
        {
            this.isSupportTimeCapField = value;
        }
    }

    /// <remarks/>
    public bool isSupportPostUpdateFirmware
    {
        get
        {
            return this.isSupportPostUpdateFirmwareField;
        }
        set
        {
            this.isSupportPostUpdateFirmwareField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSysCapNetworkCap
{

    private bool isSupportWirelessField;

    private bool isSupportWiredField;

    private bool isSupportPPPoEField;

    private bool isSupportBondField;

    private bool isSupport802_1xField;

    private bool isSupportNtpField;

    private bool isSupportFtpField;

    private bool isSupportUpnpField;

    private bool isSupportDdnsField;

    private bool isSupportHttpsField;

    private DeviceCapSysCapNetworkCapSnmpCap snmpCapField;

    private bool isSupportExtNetCfgField;

    private bool isSupportSSHField;

    private bool isSupportEZVIZField;

    private bool isSupportEhomeField;

    private bool isSupportWirelessDialField;

    private bool isSupportWirelessServerField;

    private DeviceCapSysCapNetworkCapVerificationCodeModification verificationCodeModificationField;

    private bool isSupportEZVIZQRcodeField;

    private bool isSupportEZVIZUnbindField;

    private decimal versionField;

    /// <remarks/>
    public bool isSupportWireless
    {
        get
        {
            return this.isSupportWirelessField;
        }
        set
        {
            this.isSupportWirelessField = value;
        }
    }

    /// <remarks/>
    public bool isSupportWired
    {
        get
        {
            return this.isSupportWiredField;
        }
        set
        {
            this.isSupportWiredField = value;
        }
    }

    /// <remarks/>
    public bool isSupportPPPoE
    {
        get
        {
            return this.isSupportPPPoEField;
        }
        set
        {
            this.isSupportPPPoEField = value;
        }
    }

    /// <remarks/>
    public bool isSupportBond
    {
        get
        {
            return this.isSupportBondField;
        }
        set
        {
            this.isSupportBondField = value;
        }
    }

    /// <remarks/>
    public bool isSupport802_1x
    {
        get
        {
            return this.isSupport802_1xField;
        }
        set
        {
            this.isSupport802_1xField = value;
        }
    }

    /// <remarks/>
    public bool isSupportNtp
    {
        get
        {
            return this.isSupportNtpField;
        }
        set
        {
            this.isSupportNtpField = value;
        }
    }

    /// <remarks/>
    public bool isSupportFtp
    {
        get
        {
            return this.isSupportFtpField;
        }
        set
        {
            this.isSupportFtpField = value;
        }
    }

    /// <remarks/>
    public bool isSupportUpnp
    {
        get
        {
            return this.isSupportUpnpField;
        }
        set
        {
            this.isSupportUpnpField = value;
        }
    }

    /// <remarks/>
    public bool isSupportDdns
    {
        get
        {
            return this.isSupportDdnsField;
        }
        set
        {
            this.isSupportDdnsField = value;
        }
    }

    /// <remarks/>
    public bool isSupportHttps
    {
        get
        {
            return this.isSupportHttpsField;
        }
        set
        {
            this.isSupportHttpsField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSysCapNetworkCapSnmpCap SnmpCap
    {
        get
        {
            return this.snmpCapField;
        }
        set
        {
            this.snmpCapField = value;
        }
    }

    /// <remarks/>
    public bool isSupportExtNetCfg
    {
        get
        {
            return this.isSupportExtNetCfgField;
        }
        set
        {
            this.isSupportExtNetCfgField = value;
        }
    }

    /// <remarks/>
    public bool isSupportSSH
    {
        get
        {
            return this.isSupportSSHField;
        }
        set
        {
            this.isSupportSSHField = value;
        }
    }

    /// <remarks/>
    public bool isSupportEZVIZ
    {
        get
        {
            return this.isSupportEZVIZField;
        }
        set
        {
            this.isSupportEZVIZField = value;
        }
    }

    /// <remarks/>
    public bool isSupportEhome
    {
        get
        {
            return this.isSupportEhomeField;
        }
        set
        {
            this.isSupportEhomeField = value;
        }
    }

    /// <remarks/>
    public bool isSupportWirelessDial
    {
        get
        {
            return this.isSupportWirelessDialField;
        }
        set
        {
            this.isSupportWirelessDialField = value;
        }
    }

    /// <remarks/>
    public bool isSupportWirelessServer
    {
        get
        {
            return this.isSupportWirelessServerField;
        }
        set
        {
            this.isSupportWirelessServerField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSysCapNetworkCapVerificationCodeModification VerificationCodeModification
    {
        get
        {
            return this.verificationCodeModificationField;
        }
        set
        {
            this.verificationCodeModificationField = value;
        }
    }

    /// <remarks/>
    public bool isSupportEZVIZQRcode
    {
        get
        {
            return this.isSupportEZVIZQRcodeField;
        }
        set
        {
            this.isSupportEZVIZQRcodeField = value;
        }
    }

    /// <remarks/>
    public bool isSupportEZVIZUnbind
    {
        get
        {
            return this.isSupportEZVIZUnbindField;
        }
        set
        {
            this.isSupportEZVIZUnbindField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSysCapNetworkCapSnmpCap
{

    private bool isSupportField;

    /// <remarks/>
    public bool isSupport
    {
        get
        {
            return this.isSupportField;
        }
        set
        {
            this.isSupportField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSysCapNetworkCapVerificationCodeModification
{

    private DeviceCapSysCapNetworkCapVerificationCodeModificationVerificationCodeType verificationCodeTypeField;

    private DeviceCapSysCapNetworkCapVerificationCodeModificationVerificationCodeModify verificationCodeModifyField;

    /// <remarks/>
    public DeviceCapSysCapNetworkCapVerificationCodeModificationVerificationCodeType verificationCodeType
    {
        get
        {
            return this.verificationCodeTypeField;
        }
        set
        {
            this.verificationCodeTypeField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSysCapNetworkCapVerificationCodeModificationVerificationCodeModify verificationCodeModify
    {
        get
        {
            return this.verificationCodeModifyField;
        }
        set
        {
            this.verificationCodeModifyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSysCapNetworkCapVerificationCodeModificationVerificationCodeType
{

    private string optField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string opt
    {
        get
        {
            return this.optField;
        }
        set
        {
            this.optField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSysCapNetworkCapVerificationCodeModificationVerificationCodeModify
{

    private string optField;

    private bool valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string opt
    {
        get
        {
            return this.optField;
        }
        set
        {
            this.optField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public bool Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSysCapSerialCap
{

    private byte rs485PortNumsField;

    /// <remarks/>
    public byte rs485PortNums
    {
        get
        {
            return this.rs485PortNumsField;
        }
        set
        {
            this.rs485PortNumsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSysCapVideoCap
{

    private byte videoInputPortNumsField;

    private byte videoOutputPortNumsField;

    private bool isSupportHeatmapField;

    private bool isSupportCountingField;

    private bool isSupportPreviewSwitchField;

    private bool isSupportRecodStatusField;

    private bool isSupportPrivacyMaskField;

    private bool isSupportBinocularPreviewSwitchField;

    private bool isSupportCalibCheckField;

    private bool isSupportPIPField;

    private decimal versionField;

    /// <remarks/>
    public byte videoInputPortNums
    {
        get
        {
            return this.videoInputPortNumsField;
        }
        set
        {
            this.videoInputPortNumsField = value;
        }
    }

    /// <remarks/>
    public byte videoOutputPortNums
    {
        get
        {
            return this.videoOutputPortNumsField;
        }
        set
        {
            this.videoOutputPortNumsField = value;
        }
    }

    /// <remarks/>
    public bool isSupportHeatmap
    {
        get
        {
            return this.isSupportHeatmapField;
        }
        set
        {
            this.isSupportHeatmapField = value;
        }
    }

    /// <remarks/>
    public bool isSupportCounting
    {
        get
        {
            return this.isSupportCountingField;
        }
        set
        {
            this.isSupportCountingField = value;
        }
    }

    /// <remarks/>
    public bool isSupportPreviewSwitch
    {
        get
        {
            return this.isSupportPreviewSwitchField;
        }
        set
        {
            this.isSupportPreviewSwitchField = value;
        }
    }

    /// <remarks/>
    public bool isSupportRecodStatus
    {
        get
        {
            return this.isSupportRecodStatusField;
        }
        set
        {
            this.isSupportRecodStatusField = value;
        }
    }

    /// <remarks/>
    public bool isSupportPrivacyMask
    {
        get
        {
            return this.isSupportPrivacyMaskField;
        }
        set
        {
            this.isSupportPrivacyMaskField = value;
        }
    }

    /// <remarks/>
    public bool isSupportBinocularPreviewSwitch
    {
        get
        {
            return this.isSupportBinocularPreviewSwitchField;
        }
        set
        {
            this.isSupportBinocularPreviewSwitchField = value;
        }
    }

    /// <remarks/>
    public bool isSupportCalibCheck
    {
        get
        {
            return this.isSupportCalibCheckField;
        }
        set
        {
            this.isSupportCalibCheckField = value;
        }
    }

    /// <remarks/>
    public bool isSupportPIP
    {
        get
        {
            return this.isSupportPIPField;
        }
        set
        {
            this.isSupportPIPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSysCapAudioCap
{

    private byte audioInputNumsField;

    private byte audioOutputNumsField;

    private bool mixAudioInSetField;

    private bool mixAudioOutSetField;

    private bool isSupportAudioMixingField;

    private bool isSupportAudioInConfigField;

    private bool isSupportAudioOutConfigField;

    private decimal versionField;

    /// <remarks/>
    public byte audioInputNums
    {
        get
        {
            return this.audioInputNumsField;
        }
        set
        {
            this.audioInputNumsField = value;
        }
    }

    /// <remarks/>
    public byte audioOutputNums
    {
        get
        {
            return this.audioOutputNumsField;
        }
        set
        {
            this.audioOutputNumsField = value;
        }
    }

    /// <remarks/>
    public bool mixAudioInSet
    {
        get
        {
            return this.mixAudioInSetField;
        }
        set
        {
            this.mixAudioInSetField = value;
        }
    }

    /// <remarks/>
    public bool mixAudioOutSet
    {
        get
        {
            return this.mixAudioOutSetField;
        }
        set
        {
            this.mixAudioOutSetField = value;
        }
    }

    /// <remarks/>
    public bool isSupportAudioMixing
    {
        get
        {
            return this.isSupportAudioMixingField;
        }
        set
        {
            this.isSupportAudioMixingField = value;
        }
    }

    /// <remarks/>
    public bool isSupportAudioInConfig
    {
        get
        {
            return this.isSupportAudioInConfigField;
        }
        set
        {
            this.isSupportAudioInConfigField = value;
        }
    }

    /// <remarks/>
    public bool isSupportAudioOutConfig
    {
        get
        {
            return this.isSupportAudioOutConfigField;
        }
        set
        {
            this.isSupportAudioOutConfigField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSecurityCap
{

    private byte supportUserNumsField;

    private byte userBondIpNumsField;

    private byte userBondMacNumsField;

    private bool isSupCertificateField;

    private bool issupIllegalLoginLockField;

    private bool isSupportOnlineUserField;

    private bool isSupportAnonymousField;

    private bool isSupportStreamEncryptionField;

    private DeviceCapSecurityCapSecurityVersion securityVersionField;

    private byte keyIterateNumField;

    private bool isSupportUserCheckField;

    private bool isSupportGUIDFileDataExportField;

    private bool isSupportSecurityQuestionConfigField;

    private bool isSupportGetOnlineUserListSCField;

    private DeviceCapSecurityCapSecurityLimits securityLimitsField;

    private DeviceCapSecurityCapRSAKeyLength rSAKeyLengthField;

    private bool isSupportONVIFUserManagementField;

    private DeviceCapSecurityCapWebCertificateCap webCertificateCapField;

    private bool isSupportConfigFileImportField;

    private bool isSupportConfigFileExportField;

    private DeviceCapSecurityCapCfgFileSecretKeyLenLimit cfgFileSecretKeyLenLimitField;

    private object saltField;

    private bool isSupportDeviceCertificatesManagementField;

    private bool isSupportSecurityEmailField;

    private bool isSupportEncryptCertificateField;

    private bool isSupportCertificateCustomIDField;

    private decimal versionField;

    /// <remarks/>
    public byte supportUserNums
    {
        get
        {
            return this.supportUserNumsField;
        }
        set
        {
            this.supportUserNumsField = value;
        }
    }

    /// <remarks/>
    public byte userBondIpNums
    {
        get
        {
            return this.userBondIpNumsField;
        }
        set
        {
            this.userBondIpNumsField = value;
        }
    }

    /// <remarks/>
    public byte userBondMacNums
    {
        get
        {
            return this.userBondMacNumsField;
        }
        set
        {
            this.userBondMacNumsField = value;
        }
    }

    /// <remarks/>
    public bool isSupCertificate
    {
        get
        {
            return this.isSupCertificateField;
        }
        set
        {
            this.isSupCertificateField = value;
        }
    }

    /// <remarks/>
    public bool issupIllegalLoginLock
    {
        get
        {
            return this.issupIllegalLoginLockField;
        }
        set
        {
            this.issupIllegalLoginLockField = value;
        }
    }

    /// <remarks/>
    public bool isSupportOnlineUser
    {
        get
        {
            return this.isSupportOnlineUserField;
        }
        set
        {
            this.isSupportOnlineUserField = value;
        }
    }

    /// <remarks/>
    public bool isSupportAnonymous
    {
        get
        {
            return this.isSupportAnonymousField;
        }
        set
        {
            this.isSupportAnonymousField = value;
        }
    }

    /// <remarks/>
    public bool isSupportStreamEncryption
    {
        get
        {
            return this.isSupportStreamEncryptionField;
        }
        set
        {
            this.isSupportStreamEncryptionField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSecurityCapSecurityVersion securityVersion
    {
        get
        {
            return this.securityVersionField;
        }
        set
        {
            this.securityVersionField = value;
        }
    }

    /// <remarks/>
    public byte keyIterateNum
    {
        get
        {
            return this.keyIterateNumField;
        }
        set
        {
            this.keyIterateNumField = value;
        }
    }

    /// <remarks/>
    public bool isSupportUserCheck
    {
        get
        {
            return this.isSupportUserCheckField;
        }
        set
        {
            this.isSupportUserCheckField = value;
        }
    }

    /// <remarks/>
    public bool isSupportGUIDFileDataExport
    {
        get
        {
            return this.isSupportGUIDFileDataExportField;
        }
        set
        {
            this.isSupportGUIDFileDataExportField = value;
        }
    }

    /// <remarks/>
    public bool isSupportSecurityQuestionConfig
    {
        get
        {
            return this.isSupportSecurityQuestionConfigField;
        }
        set
        {
            this.isSupportSecurityQuestionConfigField = value;
        }
    }

    /// <remarks/>
    public bool isSupportGetOnlineUserListSC
    {
        get
        {
            return this.isSupportGetOnlineUserListSCField;
        }
        set
        {
            this.isSupportGetOnlineUserListSCField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSecurityCapSecurityLimits SecurityLimits
    {
        get
        {
            return this.securityLimitsField;
        }
        set
        {
            this.securityLimitsField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSecurityCapRSAKeyLength RSAKeyLength
    {
        get
        {
            return this.rSAKeyLengthField;
        }
        set
        {
            this.rSAKeyLengthField = value;
        }
    }

    /// <remarks/>
    public bool isSupportONVIFUserManagement
    {
        get
        {
            return this.isSupportONVIFUserManagementField;
        }
        set
        {
            this.isSupportONVIFUserManagementField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSecurityCapWebCertificateCap WebCertificateCap
    {
        get
        {
            return this.webCertificateCapField;
        }
        set
        {
            this.webCertificateCapField = value;
        }
    }

    /// <remarks/>
    public bool isSupportConfigFileImport
    {
        get
        {
            return this.isSupportConfigFileImportField;
        }
        set
        {
            this.isSupportConfigFileImportField = value;
        }
    }

    /// <remarks/>
    public bool isSupportConfigFileExport
    {
        get
        {
            return this.isSupportConfigFileExportField;
        }
        set
        {
            this.isSupportConfigFileExportField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSecurityCapCfgFileSecretKeyLenLimit cfgFileSecretKeyLenLimit
    {
        get
        {
            return this.cfgFileSecretKeyLenLimitField;
        }
        set
        {
            this.cfgFileSecretKeyLenLimitField = value;
        }
    }

    /// <remarks/>
    public object salt
    {
        get
        {
            return this.saltField;
        }
        set
        {
            this.saltField = value;
        }
    }

    /// <remarks/>
    public bool isSupportDeviceCertificatesManagement
    {
        get
        {
            return this.isSupportDeviceCertificatesManagementField;
        }
        set
        {
            this.isSupportDeviceCertificatesManagementField = value;
        }
    }

    /// <remarks/>
    public bool isSupportSecurityEmail
    {
        get
        {
            return this.isSupportSecurityEmailField;
        }
        set
        {
            this.isSupportSecurityEmailField = value;
        }
    }

    /// <remarks/>
    public bool isSupportEncryptCertificate
    {
        get
        {
            return this.isSupportEncryptCertificateField;
        }
        set
        {
            this.isSupportEncryptCertificateField = value;
        }
    }

    /// <remarks/>
    public bool isSupportCertificateCustomID
    {
        get
        {
            return this.isSupportCertificateCustomIDField;
        }
        set
        {
            this.isSupportCertificateCustomIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSecurityCapSecurityVersion
{

    private string optField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string opt
    {
        get
        {
            return this.optField;
        }
        set
        {
            this.optField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSecurityCapSecurityLimits
{

    private DeviceCapSecurityCapSecurityLimitsLoginPasswordLenLimit loginPasswordLenLimitField;

    private DeviceCapSecurityCapSecurityLimitsSecurityAnswerLenLimit securityAnswerLenLimitField;

    /// <remarks/>
    public DeviceCapSecurityCapSecurityLimitsLoginPasswordLenLimit LoginPasswordLenLimit
    {
        get
        {
            return this.loginPasswordLenLimitField;
        }
        set
        {
            this.loginPasswordLenLimitField = value;
        }
    }

    /// <remarks/>
    public DeviceCapSecurityCapSecurityLimitsSecurityAnswerLenLimit SecurityAnswerLenLimit
    {
        get
        {
            return this.securityAnswerLenLimitField;
        }
        set
        {
            this.securityAnswerLenLimitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSecurityCapSecurityLimitsLoginPasswordLenLimit
{

    private byte minField;

    private byte maxField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte min
    {
        get
        {
            return this.minField;
        }
        set
        {
            this.minField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte max
    {
        get
        {
            return this.maxField;
        }
        set
        {
            this.maxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSecurityCapSecurityLimitsSecurityAnswerLenLimit
{

    private byte minField;

    private byte maxField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte min
    {
        get
        {
            return this.minField;
        }
        set
        {
            this.minField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte max
    {
        get
        {
            return this.maxField;
        }
        set
        {
            this.maxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSecurityCapRSAKeyLength
{

    private string optField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string opt
    {
        get
        {
            return this.optField;
        }
        set
        {
            this.optField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSecurityCapWebCertificateCap
{

    private DeviceCapSecurityCapWebCertificateCapCertificateType certificateTypeField;

    /// <remarks/>
    public DeviceCapSecurityCapWebCertificateCapCertificateType CertificateType
    {
        get
        {
            return this.certificateTypeField;
        }
        set
        {
            this.certificateTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSecurityCapWebCertificateCapCertificateType
{

    private string optField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string opt
    {
        get
        {
            return this.optField;
        }
        set
        {
            this.optField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapSecurityCapCfgFileSecretKeyLenLimit
{

    private byte minField;

    private byte maxField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte min
    {
        get
        {
            return this.minField;
        }
        set
        {
            this.minField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte max
    {
        get
        {
            return this.maxField;
        }
        set
        {
            this.maxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapRacmCap
{

    private DeviceCapRacmCapSecurityLog securityLogField;

    /// <remarks/>
    public DeviceCapRacmCapSecurityLog SecurityLog
    {
        get
        {
            return this.securityLogField;
        }
        set
        {
            this.securityLogField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.isapi.org/ver20/XMLSchema")]
public partial class DeviceCapRacmCapSecurityLog
{

    private bool isSupportLogServerField;

    /// <remarks/>
    public bool isSupportLogServer
    {
        get
        {
            return this.isSupportLogServerField;
        }
        set
        {
            this.isSupportLogServerField = value;
        }
    }
}
